// Action Types
const LOGIN_STATUS = "LOGIN_STATUS"
// const GET_STATES = "GET_STATES"
const SET_STATE = "SET_STATES"
const SET_CAMP_LIST = "SET_CAMP_LIST"
const SET_PARK_LIST = "SET_PARK_LIST"
const CAMPS_LOADED = "CAMPS_LOADED"
const PARKS_LOADED = "PARKS_LOADED"
const SET_USER_CAMPS = "SET_USER_CAMPS"
const SET_USER_PARKS = "SET_USER_PARKS"
// const USER_CAMP_DELETED = "USER_CAMP_DELETED"
// const USER_PARK_DELETED = "USER_PARK_DELETED"
// const USER_CAMPS_LOADED = "USER_CAMPS_LOADED"
// const USER_PARKS_LOADED = "USER_PARKS_LOADED"
const SET_CURRENT_PARK = "SET_CURRENT_PARK"
// const HAS_CAMPGROUNDS = "HAS_CAMPGROUNDS"

module.exports = {
  LOGIN_STATUS,
  SET_STATE,
  SET_CAMP_LIST,
  SET_PARK_LIST,
  SET_USER_CAMPS,
  SET_USER_PARKS,
  SET_CURRENT_PARK,
  CAMPS_LOADED,
  PARKS_LOADED
}